spring.application.name=complaints

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=${PORT:8080}
spring.data.rest.base-path=/api
spring.jpa.hibernate.ddl-auto=none

spring.main.banner-mode=off
logging.level.root=warn
#logging.level.root=info
logging.level.org.springframework.security=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#jwt configuration
jwt.rsa-private-key=${JWT_RSA_PRIVATE_KEY:classpath:keys/private.pem}
jwt.rsa-public-key=${JWT_RSA_PUBLIC_KEY:classpath:keys/public.pem}



spring.thymeleaf.check-template-location=false

#C:/Users/fl8000/Desktop/our_project/complaint/my_db

#add email service verification
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#
#logging.level.org.hibernate.exception=ERROR
#logging.level.org.springframework.web=ERROR
#logging.level.org.springframework=ERROR
